#! /bin/bash
#Finding the factprial of $1

if [[ $# -ne 1 ]]
then
echo -e  " \e[1;31m Usage: fact a \e[0m" 
else
res=1;
i=$1;
while [ $i -ge 1 ]
do
  res=$[ $res*$i ]
  let i--
done

echo "$1! = $res"
fi
